"""
Library of emojis.
"""

emojis = {
    "smile": "😊",
    "laugh": "😂",
    "wink": "😉",
    "heart_eyes": "😍",
    "thinking": "🤔",
    "cry": "😢",
    "angry": "😠",
    "surprised": "😲",
    "cool": "😎",
    "sleepy": "😴",
    "cat": "🐱",
    "dog": "🐶",
    "mouse": "🐭",
    "rabbit": "🐰",
    "fox": "🦊",
    "panda": "🐼",
    "lion": "🦁",
    "tiger": "🐯",
    "bear": "🐻",
    "unicorn": "🦄",
    "apple": "🍎",
    "banana": "🍌",
    "cherry": "🍒",
    "watermelon": "🍉",
    "grapes": "🍇",
    "strawberry": "🍓",
    "pizza": "🍕",
    "burger": "🍔",
    "fries": "🍟",
    "ice_cream": "🍦",
    "sun": "☀️",
    "cloud": "☁️",
    "rain": "🌧️",
    "snowflake": "❄️",
    "lightning": "⚡",
    "flower": "🌸",
    "tree": "🌳",
    "cactus": "🌵",
    "mountain": "⛰️",
    "wave": "🌊",
    "car": "🚗",
    "bike": "🚴",
    "airplane": "✈️",
    "train": "🚆",
    "phone": "📱",
    "computer": "💻",
    "camera": "📷",
    "book": "📚",
    "gift": "🎁",
    "clock": "⏰",
    "heart": "❤️",
    "star": "⭐",
    "check_mark": "✔️",
    "cross_mark": "❌",
    "question_mark": "❓",
    "exclamation_mark": "❗",
    "peace": "☮️",
    "infinity": "♾️",
    "recycle": "♻️",
    "warning": "⚠️"
}
